version: '3.8'
services:
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "products"]
      interval: 5s
      retries: 10
    networks:
      - backend

  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "inventory"]
      interval: 5s
      retries: 10
    networks:
      - backend

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      product-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      product-service:
        condition: service_started
      inventory-db:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
