version: '3.8'

services:
  product-db:
    image: postgres:15
    container_name: product-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  product-service:
    build: .
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - product-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata:
