server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://product-db:5432/productdb
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  logging:
    level:
    com.example.product: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

logging:
  level:
    org.springframework.web: INFO
    com.example.product: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
