server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventorydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  logging:
    level:
    com.example.product: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

logging:
  level:
    org.springframework.web: INFO
    com.example.product: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

product-service:
  url: http://localhost:8081/api/v1/products