server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://inventory-db:5432/inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

product-service:
  url: http://product-service:8081/api/v1/products

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
