services:
  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Expone el puerto 5432 del contenedor en tu máquina como 5433
    volumes:
      - inventory-data:/var/lib/postgresql/data
    restart: unless-stopped  # Opcional: reinicia si el contenedor falla

volumes:
  inventory-data:
